name: Build and test GNU
run-name: Building and testing Basins GCC on branch <${{ github.head_ref }}> to <${{ github.base_ref }}> by @${{ github.actor }}

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

defaults:
  run:
    shell: bash

jobs:    
  build_gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # Setup Python for this job
      - name: Set up Python 3.8.5
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.5
      # Run compilation and deployment
      - name: Set up configuration
        run: |
          sed -i 's/FORCE_GCC      = OFF/FORCE_GCC      = ON/g' options.cfg
      - name: Set up dependencies
        run: make requirements
      - name: Build compiled code
        run: make python
      - name: Install
        run: make install
        # Run Examples
      - name: Run examples
        run: |
          python Examples/example_basic.py
          python Examples/example_plot_basin.py
          python Examples/example_plot_composedbasin.py
          python Examples/example_skadar.py